Auction.Web/Auction/Controllers/AdminCabinetController.cs
using Auction.Business.Entities;
using Auction.Business.Services.Interfaces;
using Auction.Configure;
using Auction.Filters;
using Auction.Models;
using Autofac;
using AutoMapper;
using NLog;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Auction.Controllers.ProductController;

namespace Auction.Controllers
{
    public class AdminCabinetController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private GetAuctioneHouse _getAuctionesHouses = new GetAuctioneHouse();

        IUserService _userService;
        IProductService _productService;
        IRoles _rolesService;
        IBidService _bidService;
        ICategoryService _categoryService;
        string _path;
        string name;
        string type;
        IComponentContext _context;

        public AdminCabinetController(IComponentContext context)
        {
            _context = context;
        }
        
        [Authorize(Roles = "Admin")]
        public ActionResult AdminPanel()
        {
            return View();
        }
        

        [Authorize(Roles ="Admin")]
        public ActionResult ShowAllUsers()
        {
            var users = _userService.GetUsers();
            List<LoginUserModel> newUsers = new List<LoginUserModel>();

            foreach(var n in users)
            {
                var user = Mapper.Map<LoginUserModel>(n);
                var roles = _rolesService.GetUserRoles(Guid.Parse(user.Id)).ToList();
                newUsers.Add(user);
            }
            return View(newUsers);
        }

        public ActionResult ShowAllBannedProduct()
        {
            var products = _productService.GetProducts().Where(x => x.State.Equals(State.Banned));

            List<ProductDTOModel> newProducts = new List<ProductDTOModel>();
            foreach(var n in products)
            {
                newProducts.Add(Mapper.Map<ProductDTOModel>(n));
            }

            return View(newProducts);
        }

        [Authorize(Roles ="Admin, Manager")]
        public ActionResult ExtendAuction(Guid id)
        {
            var product = _productService.product(id);
            return View(Mapper.Map<ProductModel>(product));
        }

        [HttpPost]
        public ActionResult ExtendAuction(ProductModel productModel)
        {
            productModel.State = State.Selling;
            _productService.Update(Mapper.Map<Business.Entities.Product>(productModel));

            return RedirectToAction("Index", "Product");
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            name = RouteData.Values["house"].ToString();
            _path = _getAuctionesHouses.GetPath(name).Path;
            type = _getAuctionesHouses.GetPath(name).Type;
            _userService = _context.Resolve<IUserService>(new NamedParameter("path", ConfigurationManager.AppSettings["JsonRepositoryPath"]));
            _productService = _context.Resolve<IProductService>(new NamedParameter("type", type), new NamedParameter("path", _path));
            _rolesService = _context.Resolve<IRoles>(new NamedParameter("path", ConfigurationManager.AppSettings["JsonRepositoryPath"]));
            _categoryService = _context.Resolve<ICategoryService>(new NamedParameter("type", type), new NamedParameter("path", _path));
        }

    }
}

Auction.Web/Auction/Views/AdminCabinet/AdminPanel.cshtml
@{
    ViewBag.Title = User.Identity.Name;
}


<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ДобавитьПродукт, "AddProduct", "Product")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПросмотретьВсехПользователей, "ShowAllUsers", "AdminCabinet")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПоказатьВсеПродукты, "Index", "Product")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ОСебеЛюбимом, "AddCategory", "Category")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПоказатьОтчетПоBANNEDПродуктам, "ShowAllBannedProduct", "AdminCabinet")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.РедактированиеКатегорий, "GetCategorys", "Category")</h3>

Auction.Web/Auction/Views/AdminCabinet/ExtendAuction.cshtml
@model Auction.Models.ProductModel

@{
    ViewBag.Title = "ExtendAuction";
}

<h2>@App_LocalResources.GlobalRes.ПродлитьАукцион</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.Base64Picture)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.Discription)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.Id)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.Name)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.StartPrice)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.State)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId)
            </div>

            <div class="col-md-10">
                @Html.HiddenFor(model => model.СategoryId)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(App_LocalResources.GlobalRes.ДавайНеБудем, "Index")
</div>

Auction.Web/Auction/Views/AdminCabinet/ShowAllBannedProduct.cshtml
@model IEnumerable<Auction.Models.ProductDTOModel>

@{
    ViewBag.Title = "ShowAllBannedProduct";
}

<h2>@App_LocalResources.GlobalRes.ВсеПродуктыBanned</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TheRestOfTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Base64Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.СategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TheRestOfTime)
        </td>
        <td>
            <img src="data:image;base64,@item.Base64Picture" height="80" width="100" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.СategoryName)
        </td>
        <td>
            @Html.RouteLink(App_LocalResources.GlobalRes.ПродлитьАукцион, new { controller = "AdminCabinet", action = "ExtendAuction", area = "", @item.Id })
            @Html.RouteLink(App_LocalResources.GlobalRes.УдалитьПродукт, new { ccontroller = "Product", action = "DeleteProduct", area = "", @item.Id })
        </td>
    </tr>
}

</table>

Auction.Web/Auction/Views/AdminCabinet/ShowAllUsers.cshtml
@model IEnumerable<Auction.Models.LoginUserModel>

@{
    ViewBag.Title = "ShowAllUsers";
}

<h2>@App_LocalResources.GlobalRes.ЗарегистрированыеПользователи</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrionDate)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.role)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Login)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrionDate)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.role)
        </td>*@
        <td>
            @Html.RouteLink(App_LocalResources.GlobalRes.Удалить, new { controller = "User", action = "DeleteUsers", area = "", @item.Id })
            @Html.RouteLink(App_LocalResources.GlobalRes.ПовыситьСтатусПользователя, new { controller = "User", action = "UpStatusUser", area = "", @item.Id })
    </tr>
}

</table>