Auction.Web/Auction/Controllers/BidController.cs
using Auction.Business.Services.Interfaces;
using Auction.Configure;
using Auction.Filters;
using Auction.Models;
using Autofac;
using AutoMapper;
using NLog;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using static Auction.Controllers.ProductController;

namespace Auction.Controllers
{
    public class BidController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        private GetAuctioneHouse _getAuctionesHouses = new GetAuctioneHouse();

        private IBidService _bidService;
        private IProductService _productService;
        private IUserService _userService;
        private ICategoryService _categoryService;
        private string _path;
        string name;
        string type;
        private readonly IComponentContext _context;
        
        public BidController(IComponentContext context)
        {
            _context = context;
            logger.Trace("Constructor BidController");
        }
        
        public DateTime GetTime(Guid id)
        {
            DateTime time = _bidService.GetTime(id);
            return time;
        }

        [Authorize]
        public ActionResult DeleteBid(Guid id)
        {
            Guid userId = _userService.GetUserId(User.Identity.Name);
            var bid = _bidService.GetBids().ToList().Find(x => x.ProductId.Equals(id) && x.UserId.Equals(userId));
            var product = _productService.GetProducts().ToList().Find(x => x.Id.Equals(bid.ProductId));
            if (product.State == State.Draft.ToString())
            {
                BidModel bidModel = Mapper.Map<BidModel>(bid);
                return View(bidModel);
            }
            return Redirect(Request.RawUrl);
        }

        [HttpPost]
        public ActionResult DeleteBid(BidModel bidModel)
        {
            Guid id = bidModel.Id;
            _bidService.DeleteBid(id);
            return RedirectToAction("Index", "Home");
        }
        
        [Authorize]
        public ActionResult CreateBid(Guid Id, string url)
        {
            try
            {
                string[] keys = ConfigurationManager.AppSettings.AllKeys;
                var product = _productService.product(Id);
                string category = _categoryService.category(product.СategoryId).Name;
                Guid userId = _userService.GetUserId(User.Identity.Name);
                var bids = _bidService.GetBids().ToList().Find(x => x.ProductId.Equals(Id) && x.UserId.Equals(userId));
                if (bids== null)
                {
                    BidModel bid = new BidModel();
                    foreach (string s in keys)
                    {
                        if (s.Equals(category))
                        {
                            bid.Price = Convert.ToDecimal(ConfigurationManager.AppSettings[s]);
                            product.StartPrice += Convert.ToDecimal(ConfigurationManager.AppSettings[s]);
                            _productService.Update(product);
                        }
                    }

                    bid.ProductId = Id;
                    bid.UserId = userId;
                    bid.Time = DateTime.Now;

                    _bidService.AddBid(Mapper.Map<Business.Entities.Bid>(bid));
                }
               else
                {
                    foreach (string s in keys)
                    {
                        if (s.Equals(category))
                        {
                            bids.Price = Convert.ToDecimal(ConfigurationManager.AppSettings[s]);
                            product.StartPrice += Convert.ToDecimal(ConfigurationManager.AppSettings[s]);
                            _productService.Update(product);
                            _bidService.Update(bids);
                        }
                    }
                }

            }
            catch (ConfigurationErrorsException e)
            {
                ModelState.AddModelError("", e.Message);
            }
            return Redirect(url);

        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            name = RouteData.Values["house"].ToString();
            _path = _getAuctionesHouses.GetPath(name).Path;
            type = _getAuctionesHouses.GetPath(name).Type;
            _bidService = _context.Resolve<IBidService>(new NamedParameter("type", type), new NamedParameter("path", _path));
            _productService = _context.Resolve<IProductService>(new NamedParameter("type", type), new NamedParameter("path", _path));
            _userService = _context.Resolve<IUserService>(new NamedParameter("path", ConfigurationManager.AppSettings["JsonRepositoryPath"]));
            _categoryService = _context.Resolve<ICategoryService>(new NamedParameter("type", type), new NamedParameter("path", _path));
        }

    }
}

Auction.Web/Auction/Controllers/CabinetController.cs
using Auction.Business.Services.Interfaces;
using Auction.Filters;
using Auction.Models;
using Autofac;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Auction.Controllers.ProductController;

namespace Auction.Controllers
{
    [Culture]
    public class CabinetController : Controller
    {
        IUserService _userService;
        IProductService _productService;
        IRoles _rolesService;
        IBidService _bidService;
        ICategoryService _categoryService;
        string _path;
        IComponentContext _context;

        public CabinetController(IComponentContext context)
        {
            _path = ConfigurationManager.AppSettings["JsonRepositoryPath"];
            _context = context;
            _userService = context.Resolve<IUserService>(new NamedParameter("path", _path));
            _productService = context.Resolve<IProductService>(new NamedParameter("path", _path));
            _rolesService = context.Resolve<IRoles>(new NamedParameter("path", _path));
            _categoryService = context.Resolve<ICategoryService>(new NamedParameter("path", _path));
        }


        // GET: Cabinet
        [Authorize]
        public ActionResult UserPanel()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AdminPanel()
        {
            return View();
        }

        [Authorize(Roles = "Manager")]
        public ActionResult ManagerPanel()
        {
            return View();
        }

        [Authorize(Roles ="Admin")]
        public ActionResult ShowAllUsers()
        {
            var users = _userService.GetUsers();
            List<LoginUserModel> newUsers = new List<LoginUserModel>();

            foreach(var n in users)
            {
                newUsers.Add(Mapper.Map<LoginUserModel>(n));
            }
            return View(newUsers);
        }

        public ActionResult ShowAllBannedProduct()
        {
            var products = _productService.GetProducts().Where(x => x.State.Equals(State.Banned));

            List<ProductDTOModel> newProducts = new List<ProductDTOModel>();
            foreach(var n in products)
            {
                newProducts.Add(Mapper.Map<ProductDTOModel>(n));
            }

            return View(newProducts);
        }

        [Authorize(Roles ="Admin, Manager")]
        public ActionResult ExtendAuction(Guid id)
        {
            var product = _productService.product(id);
            return View(Mapper.Map<ProductDTOModel>(product));
        }

        [HttpPost]
        public ActionResult ExtendAuction(ProductDTOModel productModel)
        {
            productModel.State = State.Selling;
            _productService.Update(Mapper.Map<Business.Entities.Product>(productModel));

            return RedirectToAction("Index", "Product");
        }

        public ActionResult ShowMyProduct()
        {
            string userName = User.Identity.Name;
            Guid id = _userService.GetUserId(userName);
            var products = _productService.GetProducts().Where(x => x.UserId.Equals(id));
            List<ProductDTOModel> myProduct = new List<ProductDTOModel>();

            foreach (var product in products)
            {
                product.StartDate = DateTime.Now;
                ProductDTOModel newProduct = new ProductDTOModel();
                newProduct = Mapper.Map<ProductDTOModel>(product);
                newProduct.TheRestOfTime = product.Duration.Subtract(product.StartDate);
                if (newProduct.TheRestOfTime <= TimeSpan.Zero)
                {
                    newProduct.TheRestOfTime = TimeSpan.Zero;
                    newProduct.State = State.Banned;
                }
                var name = _categoryService.category(product.СategoryId);
                newProduct.СategoryName = name.Name;
                myProduct.Add(newProduct);
            }

            return View(myProduct);
        }


    }
}

Auction.Web/Auction/Views/Cabinet/AdminPanel.cshtml
@{
    ViewBag.Title = User.Identity.Name;
}


<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ДобавитьКатегорию, "AddCategory", "Category")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ДобавитьПродукт, "AddProduct", "Product")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПросмотретьВсехПользователей, "ShowAllUsers", "Cabinet")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПоказатьВсеПродукты, "GetProducts", "Product")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ОСебеЛюбимом, "AddCategory", "Category")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПоказатьОтчетПоBANNEDПродуктам, "ShowAllBannedProduct", "Cabinet")</h3>

Auction.Web/Auction/Views/Cabinet/ExtendAuction.cshtml
@model Auction.Models.ProductModel

@{
    ViewBag.Title = "ExtendAuction";
}

<h2>@App_LocalResources.GlobalRes.ПродлитьАукцион</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProductModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="form-group">
                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(App_LocalResources.GlobalRes.ДавайНеБудем, "Index")
</div>

Auction.Web/Auction/Views/Cabinet/ManagerPanel.cshtml
@{
    ViewBag.Title = User.Identity.Name;
}

<h3>@Html.ActionLink(App_LocalResources.GlobalRes.РедактироватьЛичныеДанные, "AddCategory", "Category")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПросмотретьСписокВыставленныхСвоихТоваров, "ShowMyProduct", "Cabinet")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПросмотретьСписокМоихСтавок, "ShowMyBid", "Bid")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ДобавитьПродукт, "AddProduct", "Product")</h3>

Auction.Web/Auction/Views/Cabinet/ShowAllBannedProduct.cshtml
@model IEnumerable<Auction.Models.ProductDTOModel>

@{
    ViewBag.Title = "ShowAllBannedProduct";
}

<h2>@App_LocalResources.GlobalRes.ВсеПродуктыBanned</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TheRestOfTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Base64Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.СategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TheRestOfTime)
        </td>
        <td>
            <img src="data:image;base64,@item.Base64Picture" height="80" width="100" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.СategoryName)
        </td>
        <td>
            @Html.RouteLink(App_LocalResources.GlobalRes.ПродлитьАукцион, new { controller = "Cabinet", action = "ExtendAuction", area = "", @item.Id })
            @Html.RouteLink(App_LocalResources.GlobalRes.УдалитьПродукт, new { ccontroller = "Product", action = "DeleteProduct", area = "", @item.Id })
        </td>
    </tr>
}

</table>

Auction.Web/Auction/Views/Cabinet/ShowAllUsers.cshtml
@model IEnumerable<Auction.Models.LoginUserModel>

@{
    ViewBag.Title = "ShowAllUsers";
}

<h2>@App_LocalResources.GlobalRes.ЗарегистрированыеПользователи</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegistrionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.role)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Login)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegistrionDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.role)
        </td>
        <td>
            @Html.RouteLink(App_LocalResources.GlobalRes.Удалить, new { controller = "User", action = "DeleteUsers", area = "", @item.Id })
            @Html.RouteLink(App_LocalResources.GlobalRes.ПовыситьСтатусПользователя, new { controller = "User", action = "UpStatusUser", area = "", @item.Id })
    </tr>
}

</table>

Auction.Web/Auction/Views/Cabinet/ShowMyProduct.cshtml
@model IEnumerable<Auction.Models.ProductDTOModel>

@{
    ViewBag.Title = "ShowMyProduct";
}
@{ 
    string url = Request.Url.ToString();
}
<h2>Мои товары</h2>

<p>
    @Html.ActionLink(@App_LocalResources.GlobalRes.ДобавитьНовый, "AddProduct","Product")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TheRestOfTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Base64Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.СategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discription)
        </td>
        <td>
            @Html.DisplayFor(modellItem => item.TheRestOfTime.Days)d
            @Html.DisplayFor(modellItem => item.TheRestOfTime.Hours)h
            @Html.DisplayFor(modellItem => item.TheRestOfTime.Minutes)m
            @Html.DisplayFor(modellItem => item.TheRestOfTime.Seconds)s
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            <img src="data:image;base64,@item.Base64Picture" height="80" width="100" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.СategoryName)
        </td>
        <td>@Html.RouteLink(App_LocalResources.GlobalRes.Изменить, new { controller = "Product", action = "EditProduct", area = "", @item.Id,url })</td>
        <td>@Html.RouteLink(App_LocalResources.GlobalRes.Удалить, new { controller = "Product", action = "DeleteProduct", area = "", @item.Id,url }) </td>
        
    </tr>
}

</table>

Auction.Web/Auction/Views/Cabinet/UserPanel.cshtml
@{
    ViewBag.Title = User.Identity.Name;
}

<h3>@Html.ActionLink(App_LocalResources.GlobalRes.РедактироватьЛичныеДанные, "AddCategory", "Category")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПросмотретьСписокВыставленныхСвоихТоваров, "ShowMyProduct", "Cabinet")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ПросмотретьСписокМоихСтавок, "ShowMyBid", "Bid")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.ДобавитьПродукт, "AddProduct", "Product")</h3>
<h3>@Html.ActionLink(App_LocalResources.GlobalRes.СлезноПопраситьАдминаОПовышенииСтатуса, "AddProduct", "Product")</h3>